Repository subramanian-elavathur/tici-taca-toey-server, pull requests merged in 2020-07, with the labels that each got.

#17 Closes #14 Completed games not abandoned
  src/TiciTacaToeyGameEngine.ts
  src/model.ts
Labels: bug

#25 Adding testing and server start documentation
  README.md
Labels: documentation

#26 Integrating new calculateWinner function
  .vscode/launch.json
  src/TiciTacaToeyGameEngine.ts
  src/model.ts
Labels: enhancement, good first issue

#29 Refactor REGISTER_PLAYER message calls
  src/TiciTacaToeyGameEngine.ts
  src/server.ts
Labels: enhancement, good first issue
